[global]
dataFrameSerialization = "legacy"

[server]
headless = true
runOnSave = true
port = 8501
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

